"""``prepare_purchase`` on the PUBLIC Orquestra MCP surface — falsified offline.

``https://mcp.geckovision.tech/orquestra/sse`` is unauthenticated: anyone on the internet
reaches these tools. So the thing this file pins hardest is not the happy path, it is the
BOUNDARY — the tool plans and verifies, and the caller signs:

1. A clean prepare hands back an UNSIGNED transaction and an ``exact`` binding, carrying
   the FRESH blockhash rather than the stale one the builder stamped.
2. A plan that pays the buyer back is refused BEFORE the builder is asked — proven by the
   fake builder's own call count, not by trusting the order the code reads in.
3. A failed receipt returns a refusal, a revert class, and NO transaction.
4. ``network`` is asserted or nothing happens: absent, ``unknown``, and off-vocabulary
   all refuse before any transport.
5. Neither module in the path may so much as NAME a signing or broadcast identifier.

Pattern B: every transport is an injected fake. No network, no key, no cent.
"""

from __future__ import annotations

import ast
import base64
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from gecko.prepare_purchase import prepare_purchase_result
from gecko.providers.catalog_surface import OrquestraCatalogSurface
from gecko.simulate import BuiltTx

PROGRAM = "BUYuxRfhCMWavaUWxhGtPP3ksKEDZxCD5gzknk3JfAya"
USDC = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
TOKEN_PROGRAM = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
ATA_PROGRAM = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
SYSTEM_PROGRAM = "11111111111111111111111111111111"
DISCRIMINATOR = bytes.fromhex("c13ee38869d4c914")

BUYER = "49KEkqP6eq7VhuFaSK6tLqxdg9bBTmDFRTFLiGQuwg75"
#: Independently pinned, NOT regenerated by the code under test: the buyer's classic-Token
#: USDC ATA, and the ``receipts`` account the chain confirms the program owns.
BUYER_ATA = "8zR8MmJjWweSKfwJSkZtdzQ2h3DoHHnXtZkyHSfXkPTx"
JONASBAR_RECEIPTS = "H7BjEBtan8h1HXeM38fHNPN7WxQswDhF8PFwnTuQDt5V"
STORE_AUTHORITY = "8D8qFHBnvS6oMsJy7EmGTrpoZcGd3aCC3pnPLi93Ag2V"
STORE_TOKEN = "FaK5981JTnAbraeKQTjptKAHiF74Zy4upg2hoBdLnGyY"

#: What the builder stamps (its own RPC, ~4,500 blocks stale on 2026-08-12) versus what
#: the node we simulate against reports. They differ so the patch is observable.
STALE_BLOCKHASH = "6xCk4Xgb64QofLjfh5Q5sy47W5dURHagdcDWWhhoAqgo"
FRESH_BLOCKHASH = "9BbnhWs2xkDvChRxLpoPPzXKPQzZq54BQmMWubbkeYyv"

#: An IP literal, deliberately: the public-URL guard checks it WITHOUT a DNS lookup, so
#: these tests exercise the real SSRF guard and still touch no network.
RPC_URL = "https://93.184.216.34/rpc"

IDL_ORDER = [
    "receipts",
    "signer",
    "authority",
    "mint",
    "sender_token_account",
    "recipient_token_account",
    "token_program",
    "system_program",
    "associated_token_program",
]
WRITABLE = {
    "receipts",
    "signer",
    "authority",
    "sender_token_account",
    "recipient_token_account",
}


@dataclass
class FakeBuilder:
    """Assembles a REAL legacy transaction from the plan it is handed, and counts calls.

    It mirrors the observed ``/build``: the accounts come from the plan (so a wrong
    derivation shows up in the bytes) and the blockhash is the builder's own stale one.
    ``calls`` is what makes "the refusal fired BEFORE the builder" falsifiable.
    """

    calls: list[dict[str, Any]] = field(default_factory=list)

    def __call__(self, plan: Any) -> BuiltTx:
        self.calls.append(dict(plan))
        from solders.hash import Hash
        from solders.instruction import AccountMeta, Instruction
        from solders.message import Message
        from solders.pubkey import Pubkey
        from solders.transaction import Transaction

        accounts = plan["accounts"]
        metas = [
            AccountMeta(
                pubkey=Pubkey.from_string(accounts[name]),
                is_signer=name == "signer",
                is_writable=name in WRITABLE,
            )
            for name in IDL_ORDER
        ]
        instruction = Instruction(
            program_id=Pubkey.from_string(PROGRAM),
            data=DISCRIMINATOR + b"\x00" * 8,
            accounts=metas,
        )
        message = Message.new_with_blockhash(
            [instruction],
            Pubkey.from_string(str(plan["feePayer"])),
            Hash.from_string(STALE_BLOCKHASH),
        )
        raw = bytes(Transaction.new_unsigned(message))
        return BuiltTx(tx=base64.b64encode(raw).decode(), encoding="base64")


@dataclass
class FakeRpc:
    """A replaying transport that records every method it was asked for.

    It also serves ONE storefront, because the tool now reads the merchant and the mint
    from the store's own account rather than a hardcoded table. `account=None` is a node
    that has no such account — the "no store by that name" case, which must refuse.
    """

    err: Any | None = None
    units: int = 42_494
    calls: list[str] = field(default_factory=list)
    #: Set lazily in __post_init__ so the default is jonasbar/Water, the store every
    #: pre-existing test in this file buys from.
    account: bytes | None = None
    owner: str = PROGRAM
    serve_store: bool = True
    reads: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        if self.account is None and self.serve_store:
            from tests.test_store_directory import encode_store

            self.account = encode_store(
                "jonasbar",
                products=[("Water", 100_000, 6)],
                authority=STORE_AUTHORITY,
            )

    def __call__(self, url: str, method: str, params: list[Any]) -> dict[str, Any]:
        self.calls.append(method)
        if method == "getAccountInfo":
            self.reads.append(str(params[0]))
            if self.account is None:
                return {"result": {"value": None}}
            return {
                "result": {
                    "value": {
                        "owner": self.owner,
                        "data": [base64.b64encode(self.account).decode(), "base64"],
                    }
                }
            }
        if method == "getLatestBlockhash":
            return {
                "result": {
                    "value": {
                        "blockhash": FRESH_BLOCKHASH,
                        "lastValidBlockHeight": 371_004_211,
                    }
                }
            }
        if method == "simulateTransaction":
            return {
                "result": {
                    "context": {"slot": 371_004_061},
                    "value": {
                        "err": self.err,
                        "logs": [
                            "Program BUYuxRfhCMWavaUWxhGtPP3ksKEDZxCD5gzknk3JfAya invoke [1]",
                            "Program log: instruction: MakePurchase",
                        ],
                        "unitsConsumed": self.units,
                    },
                }
            }
        raise AssertionError(f"unexpected RPC method {method}")


#: "the key was not supplied at all", which is a different case from a supplied ``None``.
_ABSENT = object()


def _prepare(
    builder: FakeBuilder | None = None,
    rpc: FakeRpc | None = None,
    _drop_network: bool = False,
    **overrides: Any,
) -> dict[str, Any]:
    args: dict[str, Any] = {
        "store": "jonasbar",
        "product": "Water",
        "buyer": BUYER,
        "network": "mainnet",
        "rpc_url": RPC_URL,
        "table": 11,
    }
    args.update(overrides)
    if _drop_network:
        args.pop("network")
    return prepare_purchase_result(
        args,
        build_call=builder or FakeBuilder(),
        rpc_call=rpc or FakeRpc(),
    )


def _blockhash_of(transaction_base64: str) -> str:
    from solders.transaction import VersionedTransaction

    raw = base64.b64decode(transaction_base64)
    return str(VersionedTransaction.from_bytes(raw).message.recent_blockhash)


# --- 1. the clean path ----------------------------------------------------------


def test_a_clean_prepare_returns_an_unsigned_transaction_bound_exactly() -> None:
    builder, rpc = FakeBuilder(), FakeRpc()
    out = _prepare(builder, rpc)

    assert out["refused"] is False
    assert out["status"] == "pass"
    assert out["units_consumed"] == 42_494
    assert out["binding_strength"] == "exact"
    assert isinstance(out["binding"], str) and len(out["binding"]) == 64
    assert out["network"] == "mainnet"

    transaction = out["transaction"]
    assert transaction["signed"] is False
    assert transaction["encoding"] == "base64"
    # The bytes carry the node's FRESH blockhash, not the stale one the builder stamped.
    assert _blockhash_of(transaction["unsigned_transaction"]) == FRESH_BLOCKHASH
    assert out["expires"]["blockhash"] == FRESH_BLOCKHASH
    assert out["expires"]["last_valid_block_height"] == 371_004_211

    # The plan was DERIVED locally and matches addresses pinned outside this code path.
    plan = {entry["account"]: entry for entry in out["accounts"]}
    assert plan["receipts"]["address"] == JONASBAR_RECEIPTS
    assert plan["sender_token_account"]["address"] == BUYER_ATA
    assert plan["recipient_token_account"]["address"] == STORE_TOKEN
    assert plan["signer"]["address"] == BUYER
    # every account says what it IS in this instruction
    assert plan["authority"]["writable"] is True
    assert plan["authority"]["signer"] is False
    assert plan["signer"]["signer"] is True
    assert all(entry["role"] for entry in out["accounts"])

    assert builder.calls and builder.calls[0]["accounts"]["signer"] == BUYER
    # The storefront is READ FIRST — before a blockhash is fetched and before anything is
    # simulated — so a store that cannot be resolved costs neither.
    assert rpc.calls == ["getAccountInfo", "getLatestBlockhash", "simulateTransaction"]


def test_the_result_carries_no_payloads_and_nothing_is_persisted() -> None:
    # Invariant #1: a receipt's metadata, never the node's response body.
    out = _prepare()
    banned = {"logs", "logs_tail", "err", "headers", "authorization", "response"}
    assert not banned & set(out)
    assert "logs" not in str(out).lower()


# --- 2. the refusal that must beat the builder ----------------------------------


def test_a_self_paying_purchase_is_refused_before_the_builder_is_asked() -> None:
    # The buyer IS the store's authority, so ATA(signer) and ATA(authority) collapse to
    # one address and the purchase would pay the buyer back. Observed live: /build
    # answered HTTP 200 to exactly this.
    builder, rpc = FakeBuilder(), FakeRpc()
    out = _prepare(builder, rpc, buyer=STORE_AUTHORITY)

    assert out["refused"] is True
    assert out["code"] == "plan-refused"
    assert "same-token-account" in out["reason"]
    assert "transaction" not in out
    assert builder.calls == [], "the plan reached the builder"
    # The store read is the ONE call a refused plan may have made: the merchant has to be
    # known before the plan can be judged wrong. Nothing was built and nothing simulated.
    assert rpc.calls == ["getAccountInfo"], "the plan reached the network"


# --- 3. a receipt that did not pass ---------------------------------------------


def test_a_failed_receipt_returns_the_revert_class_and_no_transaction() -> None:
    rpc = FakeRpc(err={"InstructionError": [0, {"Custom": 6003}]})
    out = _prepare(FakeBuilder(), rpc)

    assert out["refused"] is True
    assert out["code"] == "receipt-failed"
    assert out["status"] == "fail"
    assert out["revert_class"]
    assert "transaction" not in out


# --- 4. the network is asserted, never inferred ---------------------------------


def test_a_missing_or_unknown_network_refuses_before_any_transport() -> None:
    # `unknown` is a legal answer and it refuses; a URL is not a network, because a fork
    # proxy answers at any hostname.
    for network in (_ABSENT, None, "unknown", "https://api.mainnet-beta.solana.com", 7):
        builder, rpc = FakeBuilder(), FakeRpc()
        overrides: dict[str, Any] = {} if network is _ABSENT else {"network": network}
        out = _prepare(builder, rpc, _drop_network=network is _ABSENT, **overrides)
        assert out["refused"] is True, network
        assert out["code"] == "network-not-asserted", network
        assert "transaction" not in out
        assert builder.calls == [] and rpc.calls == []


def test_an_unknown_store_refuses_rather_than_guessing_its_authority() -> None:
    """The node answers, and what it answers with is not the store that was asked for.

    The address was DERIVED from the name, so an account that calls itself something else
    means the node returned something other than what was requested. Believed, it would
    build a purchase paying a merchant the caller never named — so it refuses, having
    spent one read and built nothing.
    """
    builder, rpc = (
        FakeBuilder(),
        FakeRpc(),
    )  # the fake serves `jonasbar` for any address
    out = _prepare(builder, rpc, store="a-store-nobody-wired")
    assert out["refused"] is True
    assert out["code"] == "store-unknown"
    assert builder.calls == []
    assert rpc.calls == ["getAccountInfo"]


def test_a_buyer_that_is_not_a_pubkey_refuses() -> None:
    builder, rpc = FakeBuilder(), FakeRpc()
    out = _prepare(builder, rpc, buyer="not-a-pubkey")
    assert out["refused"] is True
    assert out["code"] == "argument-invalid"
    assert builder.calls == [] and rpc.calls == []


# --- 5. the boundary, asserted on the source itself -----------------------------


def _code_identifiers(path: Path) -> set[str]:
    """Every identifier the module's CODE uses. Docstrings and comments are ignored —
    they legitimately say "never signs"; only executable references count."""
    tree = ast.parse(path.read_text())
    identifiers: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Name):
            identifiers.add(node.id)
        elif isinstance(node, ast.Attribute):
            identifiers.add(node.attr)
        elif isinstance(node, ast.alias):
            identifiers.add(node.name.rsplit(".", 1)[-1])
            if node.asname:
                identifiers.add(node.asname)
    return identifiers


def test_no_signing_or_broadcast_identifier_exists_in_the_public_tool() -> None:
    root = Path(__file__).resolve().parent.parent
    sources = [
        root / "gecko" / "prepare_purchase.py",
        root / "gecko" / "providers" / "catalog_surface.py",
    ]
    forbidden = {
        "TransactionSigner",
        "SigningBackend",
        "Keypair",
        "sign_and_send",
        "sendTransaction",
        "send_transaction",
        "sign",
        "sign_transaction",
        "sign_message",
        "partial_sign",
        "new_signed",
        "secret_key",
        "from_seed",
        "broadcast",
    }
    for path in sources:
        leaked = forbidden & _code_identifiers(path)
        assert not leaked, f"{path.name} must not reference {sorted(leaked)} in code"


def test_the_tool_persists_nothing() -> None:
    root = Path(__file__).resolve().parent.parent / "gecko" / "prepare_purchase.py"
    used = _code_identifiers(root)
    assert not ({"open", "write_text", "write_bytes", "mkdir", "dump"} & used)


# --- the MCP surface actually serves it -----------------------------------------


def test_the_surface_dispatches_prepare_purchase() -> None:
    builder, rpc = FakeBuilder(), FakeRpc()
    surface = OrquestraCatalogSurface(
        purchase_build_call=builder, purchase_rpc_call=rpc
    )
    names = [tool["name"] for tool in surface.list_tools()]
    assert "prepare_purchase" in names

    tool = next(t for t in surface.list_tools() if t["name"] == "prepare_purchase")
    described = tool["description"].lower()
    for claim in ("unsigned", "you sign", "expires", "well-formed"):
        assert claim in described, claim
    # `network` is no longer required: omitted with no rpc_url it means mainnet, and a
    # person buying coffee should not have to name a chain. Naming a NODE still requires
    # naming the chain — see test_supplying_an_rpc_url_without_a_network_still_refuses.
    assert tool["inputSchema"]["required"] == ["store", "product", "buyer"]

    out = surface.call_tool(
        "prepare_purchase",
        {
            "store": "jonasbar",
            "product": "Water",
            "buyer": BUYER,
            "network": "mainnet",
            "rpc_url": RPC_URL,
        },
    )
    assert out["refused"] is False
    assert out["transaction"]["signed"] is False


# --- the affordance: what an agent does NEXT ----------------------------------
# The result already carried everything needed to PRODUCE a signature; it carried
# nothing an agent could act on. `who_signs` was prose. These pin the machine-readable
# next step and the submit target — the two fields that turn a check into a loop.


def test_the_result_says_what_to_do_next_in_a_shape_an_agent_can_act_on() -> None:
    out = _prepare()
    step = out["next_step"]

    # The order is the whole point: sign, verify, THEN submit.
    assert [s["step"] for s in step["do"]] == ["sign", "verify", "submit"]
    sign, verify, submit = step["do"]

    # SIGN carries the exact bytes to hand over — not a pointer, not a description.
    assert sign["transaction"] == out["transaction"]["unsigned_transaction"]
    assert sign["encoding"] == "base64"
    # VERIFY names our own keyless tool and the binding to check against.
    assert verify["tool"] == "verify_signed_transaction"
    assert verify["binding"] == out["binding"]
    # SUBMIT names the node these bytes can actually reach.
    assert submit["rpc_url"] == RPC_URL


def test_the_next_step_names_a_shape_rather_than_a_vendor() -> None:
    """Signer-agnostic on purpose. Three signers take the identical primitive (base64 in,
    signed base64 out), so naming one in the contract would make a fourth need a change
    from us. Known signers may be listed as EXAMPLES; none may be required."""
    step = _prepare()["next_step"]
    sign = step["do"][0]

    assert "tool" not in sign, "naming one signer's tool would be an integration"
    assert sign["signers_known_to_work"], "examples help; they must not be the contract"


def test_each_signer_hint_says_how_to_ADD_it_not_just_that_it_exists() -> None:
    """A caller with no signer mounted cannot act on "PayBox reaches Claude web".

    That names a product, not a next move — so the loop stalls at the one step we do not
    perform. Carrying the connector lets the agent say exactly what to add AT THE MOMENT a
    signature is needed, instead of the user having to know in advance that two connectors
    are involved.

    This is the alternative to brokering the sign-in ourselves, which would mean holding an
    access token that authorises spending from someone's wallet — a path to a key, which
    this module's first line and the public docs both say does not exist. The friction is a
    DISCOVERY problem and gets a discovery fix.
    """
    signers = _prepare()["next_step"]["do"][0]["signers_known_to_work"]

    assert len(signers) >= 3
    for signer in signers:
        assert signer["connector"], f"{signer['name']} says nothing about how to add it"
        assert signer["how_to_add"]
        assert signer["reaches"]

    paybox = next(s for s in signers if s["name"] == "PayBox")
    assert paybox["connector"] == "https://api.paybox.sh/mcp"
    # The one that reaches the surface our acceptance test names must say so plainly.
    assert "Claude web" in paybox["reaches"]


def test_no_signer_hint_asks_the_caller_to_hand_US_a_credential() -> None:
    """The boundary, pinned where it would be easiest to erode.

    Brokering a signer's OAuth would remove one connector from the user's setup and put a
    spend-authorising token in our hands — the exact trade this whole path refuses. Nothing
    in the hints may ask for a key, a token, or a sign-in TO US.
    """
    blob = json.dumps(_prepare()["next_step"]).lower()

    for forbidden in ("api_key", "secret", "private key", "sign in to gecko"):
        assert forbidden not in blob, f"the handoff asks for {forbidden!r}"


def test_the_submit_target_is_the_node_that_was_actually_simulated_against() -> None:
    """The CALLER's node, echoed back — not the pinned public default.

    It matters most on a fork, where the RPC is somebody's own and appears nowhere else in
    the answer, so the one node that can accept the transaction would be missing from it.
    Asserted here on the supplied-URL case because the SSRF guard resolves DNS, and a
    made-up fork hostname is refused before any of this runs — correctly.
    """
    from gecko.prepare_purchase import DEFAULT_RPC_URLS

    out = _prepare()  # supplies RPC_URL explicitly

    assert out["submit"]["rpc_url"] == RPC_URL
    assert out["submit"]["rpc_url"] != DEFAULT_RPC_URLS["mainnet"], (
        "echoing the default instead of the caller's node would lose a fork's own RPC"
    )


def test_a_refusal_carries_no_next_step() -> None:
    """Nothing to sign, so nothing to do next. An affordance on a refusal is an
    invitation to act on bytes that do not exist."""
    out = _prepare(buyer=STORE_AUTHORITY)  # the self-paying refusal

    assert out["refused"] is True
    assert "next_step" not in out
    assert "submit" not in out


# --- ANY store, read from its own account ------------------------------------
# The tool used to look the merchant up in a hardcoded dict, so exactly ONE storefront on
# letmebuy.app was reachable through chat. The authority and the mint are written INSIDE
# the store's account, so the fix is one targeted read — never a guess, and never a
# fallback to a store the caller did not name.
#
# The encoder is imported from tests/test_store_directory.py rather than rewritten: a
# second copy of the layout is how a test starts passing against bytes the program would
# never produce.

from tests.test_store_directory import encode_store  # noqa: E402

GECKOCOFFEE_RECEIPTS = "5YMkXAYccHSGnHn9nob9xEvv6Pvka9DZWH7nTbotTu9E"
LET_ME_BUY = PROGRAM


#: A merchant that appears NOWHERE in our source — deliberately not `STORE_AUTHORITY`, so
#: a plan that fell back to the old hardcoded store would show it and fail.
OTHER_MERCHANT = "DMjTEZJuV3mpfzBNeeuFy9m47A1bj5CXVhCNVo7BEPzy"


def test_a_store_we_never_hardcoded_can_be_bought_from() -> None:
    """The ceiling this removes: one storefront was reachable, and letmebuy.app has many.

    The merchant asserted here is one we ship nowhere, so this cannot pass by falling
    back to the store that used to be the only one in the table.
    """
    rpc = FakeRpc(
        serve_store=False,
        account=encode_store("geckocoffee", authority=OTHER_MERCHANT),
    )
    out = _prepare(FakeBuilder(), rpc, store="geckocoffee", product="Espresso")

    assert out["refused"] is False, out
    assert rpc.reads, "the storefront was never read from chain"
    # The merchant and the mint came from the ACCOUNT, not from anything we shipped.
    plan = {e["account"]: e["address"] for e in out["accounts"]}
    assert plan["authority"] == OTHER_MERCHANT
    assert plan["authority"] != STORE_AUTHORITY, "fell back to the hardcoded store"
    assert plan["mint"] == USDC


def test_a_store_that_does_not_exist_refuses_and_names_nothing_else() -> None:
    """Absence is a refusal, never a fallback to a store the caller did not name."""
    builder = FakeBuilder()
    out = _prepare(builder, FakeRpc(serve_store=False, account=None), store="ghostbar")

    assert out["refused"] is True
    assert out["code"] == "store-unknown"
    assert "transaction" not in out
    assert builder.calls == [], "an unknown store reached the builder"


def test_an_account_owned_by_another_program_is_not_a_storefront() -> None:
    """The address derives from the name, so anyone can create SOMETHING there. Only the
    let_me_buy program's own account counts as a store."""
    out = _prepare(
        FakeBuilder(),
        FakeRpc(
            serve_store=False, account=encode_store("geckocoffee"), owner=SYSTEM_PROGRAM
        ),
        store="geckocoffee",
        product="Espresso",
    )

    assert out["refused"] is True
    assert out["code"] == "store-unknown"


def test_a_product_the_store_does_not_sell_refuses_with_the_real_menu() -> None:
    """The price and the mint are PER-PRODUCT facts in the store's account, so an unlisted
    product has neither — and a refusal that cannot be acted on is a shrug."""
    out = _prepare(
        FakeBuilder(),
        FakeRpc(serve_store=False, account=encode_store("geckocoffee")),
        store="geckocoffee",
        product="Lobster",
    )

    assert out["refused"] is True
    assert "Espresso" in out["reason"], "the refusal must say what IS on the menu"


def test_the_store_read_happens_before_anything_is_built() -> None:
    """A store that cannot be resolved must cost no builder call and no simulation —
    the same ordering the self-paying refusal already holds to."""
    rpc = FakeRpc(serve_store=False, account=None)
    builder = FakeBuilder()

    _prepare(builder, rpc, store="ghostbar")

    assert builder.calls == []
    assert "simulateTransaction" not in rpc.calls


#: A real SPL mint that is NOT USDC — Bonk, six decimals elsewhere but priced here as the
#: store declares. Its only job is to be a mint we hardcode nowhere.
OTHER_MINT = "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"


def test_a_store_priced_in_another_mint_is_paid_in_that_mint() -> None:
    """The mint is a PER-PRODUCT fact in the store's account, not a constant.

    Every other store in these tests happens to price in USDC, which makes a hardcoded
    `USDC_MINT` indistinguishable from a read one. This is the store that tells them
    apart — and it matters, because the mint decides which token account is credited.
    """
    rpc = FakeRpc(
        serve_store=False,
        account=encode_store(
            "bonkbar",
            products=[("Shot", 5_000_000, 5)],
            authority=OTHER_MERCHANT,
            mint=OTHER_MINT,
        ),
    )

    out = _prepare(FakeBuilder(), rpc, store="bonkbar", product="Shot")

    assert out["refused"] is False, out
    plan = {e["account"]: e["address"] for e in out["accounts"]}
    assert plan["mint"] == OTHER_MINT
    assert plan["mint"] != USDC, "fell back to a hardcoded mint"
    # …and the credited token account follows the mint, not the other way round.
    assert plan["recipient_token_account"] != STORE_TOKEN


def test_the_tools_tell_an_agent_WHEN_to_prepare() -> None:
    """The window is only a problem if the agent prepares early.

    Browsing costs nothing and expires never; preparing starts a ~40-second clock on a live
    blockhash. An agent that helpfully pre-prepares three products to compare them spends
    the whole window on transactions nobody will sign — an eager, plausible mistake that no
    refusal catches, because each of those preparations is individually correct.

    So the sequencing is stated in the tool descriptions, where a model actually reads it,
    and pinned here so it cannot be edited away while the loop still depends on it.
    """
    from gecko.prepare_purchase import PREPARE_PURCHASE_TOOL
    from gecko.store_directory import LIST_STORES_TOOL

    prepare = PREPARE_PURCHASE_TOOL["description"]
    browse = LIST_STORES_TOOL["description"]

    # prepare LATE, after the choice…
    assert "after" in prepare and "before signing" in prepare
    assert "prepare LATE" in prepare
    # …and one product per call, because the program takes no quantity.
    assert "ONE PRODUCT PER CALL" in prepare
    # …with the honest number, not the one the slot budget implies.
    assert "~40 seconds" in prepare and "finalized" in prepare
    # The browsing tool points the other way, so the pair reads as a sequence.
    assert "prepare_purchase" in browse and "expires never" in browse


def test_the_expiry_note_and_the_description_agree_on_the_number() -> None:
    """Two places tell a caller how long they have. Disagreeing is how one gets believed
    and the other quietly becomes false."""
    from gecko.prepare_purchase import PREPARE_PURCHASE_TOOL

    out = _prepare()

    assert "40" in out["expires"]["note"]
    assert "40" in PREPARE_PURCHASE_TOOL["description"]


# --- the network a coffee buyer should not have to name ----------------------
# `network` had no default so nothing could infer mainnet from an RPC URL — a fork proxy
# answers at any hostname. That guard is aimed at a DEVELOPER testing against a fork, and
# it was being charged to a person saying "buy a coffee". The dangerous confusion is a fork
# MISTAKEN FOR mainnet, and defaulting to mainnet cannot cause that.


def test_a_plain_purchase_needs_no_network() -> None:
    """The chat case: somebody says "buy a coffee at geckocoffee, table 11" and means the
    real chain. Nothing else they said could mean anything else."""
    out = _prepare(_drop_network=True, rpc_url=None)

    assert out.get("refused") is not True, out
    assert out["network"] == "mainnet"


def test_supplying_an_rpc_url_without_a_network_still_refuses() -> None:
    """The guard keeps its teeth exactly where it earned them. A caller who names a NODE
    is the fork case — that hostname proves nothing about which chain answers, so the
    network has to be said out loud."""
    out = _prepare(_drop_network=True)  # the helper supplies RPC_URL

    assert out["refused"] is True
    assert out["code"] == "network-not-asserted"
    assert "rpc_url" in out["reason"]


def test_an_explicit_network_is_still_honoured() -> None:
    assert _prepare(network="mainnet")["network"] == "mainnet"


def test_the_tool_says_where_to_GET_a_signer_before_it_is_called() -> None:
    """The discovery-timing hole a real model found.

    `signers_known_to_work` lives in the RESULT, so an agent only learns a signer connector
    exists AFTER preparing — which is after the ~40-second clock starts. It would then send
    the buyer off to add a connector while the bytes died. The options have to be readable
    BEFORE the call, which means the description.
    """
    from gecko.prepare_purchase import PREPARE_PURCHASE_TOOL

    described = PREPARE_PURCHASE_TOOL["description"]

    assert "api.paybox.sh/mcp" in described
    # …and in the order a first-time buyer needs: connect, THEN fund, THEN buy.
    assert "fund" in described.lower()
    assert "before" in described.lower()
