"""``prepare_purchase`` on the PUBLIC Orquestra MCP surface — falsified offline.

``https://mcp.geckovision.tech/orquestra/sse`` is unauthenticated: anyone on the internet
reaches these tools. So the thing this file pins hardest is not the happy path, it is the
BOUNDARY — the tool plans and verifies, and the caller signs:

1. A clean prepare hands back an UNSIGNED transaction and an ``exact`` binding, carrying
   the FRESH blockhash rather than the stale one the builder stamped.
2. A plan that pays the buyer back is refused BEFORE the builder is asked — proven by the
   fake builder's own call count, not by trusting the order the code reads in.
3. A failed receipt returns a refusal, a revert class, and NO transaction.
4. ``network`` is asserted or nothing happens: absent, ``unknown``, and off-vocabulary
   all refuse before any transport.
5. Neither module in the path may so much as NAME a signing or broadcast identifier.

Pattern B: every transport is an injected fake. No network, no key, no cent.
"""

from __future__ import annotations

import ast
import base64
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from gecko.prepare_purchase import prepare_purchase_result
from gecko.providers.catalog_surface import OrquestraCatalogSurface
from gecko.simulate import BuiltTx

PROGRAM = "BUYuxRfhCMWavaUWxhGtPP3ksKEDZxCD5gzknk3JfAya"
USDC = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
TOKEN_PROGRAM = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
ATA_PROGRAM = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
SYSTEM_PROGRAM = "11111111111111111111111111111111"
DISCRIMINATOR = bytes.fromhex("c13ee38869d4c914")

BUYER = "49KEkqP6eq7VhuFaSK6tLqxdg9bBTmDFRTFLiGQuwg75"
#: Independently pinned, NOT regenerated by the code under test: the buyer's classic-Token
#: USDC ATA, and the ``receipts`` account the chain confirms the program owns.
BUYER_ATA = "8zR8MmJjWweSKfwJSkZtdzQ2h3DoHHnXtZkyHSfXkPTx"
JONASBAR_RECEIPTS = "H7BjEBtan8h1HXeM38fHNPN7WxQswDhF8PFwnTuQDt5V"
STORE_AUTHORITY = "8D8qFHBnvS6oMsJy7EmGTrpoZcGd3aCC3pnPLi93Ag2V"
STORE_TOKEN = "FaK5981JTnAbraeKQTjptKAHiF74Zy4upg2hoBdLnGyY"

#: What the builder stamps (its own RPC, ~4,500 blocks stale on 2026-08-12) versus what
#: the node we simulate against reports. They differ so the patch is observable.
STALE_BLOCKHASH = "6xCk4Xgb64QofLjfh5Q5sy47W5dURHagdcDWWhhoAqgo"
FRESH_BLOCKHASH = "9BbnhWs2xkDvChRxLpoPPzXKPQzZq54BQmMWubbkeYyv"

#: An IP literal, deliberately: the public-URL guard checks it WITHOUT a DNS lookup, so
#: these tests exercise the real SSRF guard and still touch no network.
RPC_URL = "https://93.184.216.34/rpc"

IDL_ORDER = [
    "receipts",
    "signer",
    "authority",
    "mint",
    "sender_token_account",
    "recipient_token_account",
    "token_program",
    "system_program",
    "associated_token_program",
]
WRITABLE = {
    "receipts",
    "signer",
    "authority",
    "sender_token_account",
    "recipient_token_account",
}


@dataclass
class FakeBuilder:
    """Assembles a REAL legacy transaction from the plan it is handed, and counts calls.

    It mirrors the observed ``/build``: the accounts come from the plan (so a wrong
    derivation shows up in the bytes) and the blockhash is the builder's own stale one.
    ``calls`` is what makes "the refusal fired BEFORE the builder" falsifiable.
    """

    calls: list[dict[str, Any]] = field(default_factory=list)

    def __call__(self, plan: Any) -> BuiltTx:
        self.calls.append(dict(plan))
        from solders.hash import Hash
        from solders.instruction import AccountMeta, Instruction
        from solders.message import Message
        from solders.pubkey import Pubkey
        from solders.transaction import Transaction

        accounts = plan["accounts"]
        metas = [
            AccountMeta(
                pubkey=Pubkey.from_string(accounts[name]),
                is_signer=name == "signer",
                is_writable=name in WRITABLE,
            )
            for name in IDL_ORDER
        ]
        instruction = Instruction(
            program_id=Pubkey.from_string(PROGRAM),
            data=DISCRIMINATOR + b"\x00" * 8,
            accounts=metas,
        )
        message = Message.new_with_blockhash(
            [instruction],
            Pubkey.from_string(str(plan["feePayer"])),
            Hash.from_string(STALE_BLOCKHASH),
        )
        raw = bytes(Transaction.new_unsigned(message))
        return BuiltTx(tx=base64.b64encode(raw).decode(), encoding="base64")


@dataclass
class FakeRpc:
    """A replaying transport that records every method it was asked for."""

    err: Any | None = None
    units: int = 42_494
    calls: list[str] = field(default_factory=list)

    def __call__(self, url: str, method: str, params: list[Any]) -> dict[str, Any]:
        self.calls.append(method)
        if method == "getLatestBlockhash":
            return {
                "result": {
                    "value": {
                        "blockhash": FRESH_BLOCKHASH,
                        "lastValidBlockHeight": 371_004_211,
                    }
                }
            }
        if method == "simulateTransaction":
            return {
                "result": {
                    "context": {"slot": 371_004_061},
                    "value": {
                        "err": self.err,
                        "logs": [
                            "Program BUYuxRfhCMWavaUWxhGtPP3ksKEDZxCD5gzknk3JfAya invoke [1]",
                            "Program log: instruction: MakePurchase",
                        ],
                        "unitsConsumed": self.units,
                    },
                }
            }
        raise AssertionError(f"unexpected RPC method {method}")


#: "the key was not supplied at all", which is a different case from a supplied ``None``.
_ABSENT = object()


def _prepare(
    builder: FakeBuilder | None = None,
    rpc: FakeRpc | None = None,
    _drop_network: bool = False,
    **overrides: Any,
) -> dict[str, Any]:
    args: dict[str, Any] = {
        "store": "jonasbar",
        "product": "Water",
        "buyer": BUYER,
        "network": "mainnet",
        "rpc_url": RPC_URL,
        "table": 11,
    }
    args.update(overrides)
    if _drop_network:
        args.pop("network")
    return prepare_purchase_result(
        args,
        build_call=builder or FakeBuilder(),
        rpc_call=rpc or FakeRpc(),
    )


def _blockhash_of(transaction_base64: str) -> str:
    from solders.transaction import VersionedTransaction

    raw = base64.b64decode(transaction_base64)
    return str(VersionedTransaction.from_bytes(raw).message.recent_blockhash)


# --- 1. the clean path ----------------------------------------------------------


def test_a_clean_prepare_returns_an_unsigned_transaction_bound_exactly() -> None:
    builder, rpc = FakeBuilder(), FakeRpc()
    out = _prepare(builder, rpc)

    assert out["refused"] is False
    assert out["status"] == "pass"
    assert out["units_consumed"] == 42_494
    assert out["binding_strength"] == "exact"
    assert isinstance(out["binding"], str) and len(out["binding"]) == 64
    assert out["network"] == "mainnet"

    transaction = out["transaction"]
    assert transaction["signed"] is False
    assert transaction["encoding"] == "base64"
    # The bytes carry the node's FRESH blockhash, not the stale one the builder stamped.
    assert _blockhash_of(transaction["unsigned_transaction"]) == FRESH_BLOCKHASH
    assert out["expires"]["blockhash"] == FRESH_BLOCKHASH
    assert out["expires"]["last_valid_block_height"] == 371_004_211

    # The plan was DERIVED locally and matches addresses pinned outside this code path.
    plan = {entry["account"]: entry for entry in out["accounts"]}
    assert plan["receipts"]["address"] == JONASBAR_RECEIPTS
    assert plan["sender_token_account"]["address"] == BUYER_ATA
    assert plan["recipient_token_account"]["address"] == STORE_TOKEN
    assert plan["signer"]["address"] == BUYER
    # every account says what it IS in this instruction
    assert plan["authority"]["writable"] is True
    assert plan["authority"]["signer"] is False
    assert plan["signer"]["signer"] is True
    assert all(entry["role"] for entry in out["accounts"])

    assert builder.calls and builder.calls[0]["accounts"]["signer"] == BUYER
    assert rpc.calls == ["getLatestBlockhash", "simulateTransaction"]


def test_the_result_carries_no_payloads_and_nothing_is_persisted() -> None:
    # Invariant #1: a receipt's metadata, never the node's response body.
    out = _prepare()
    banned = {"logs", "logs_tail", "err", "headers", "authorization", "response"}
    assert not banned & set(out)
    assert "logs" not in str(out).lower()


# --- 2. the refusal that must beat the builder ----------------------------------


def test_a_self_paying_purchase_is_refused_before_the_builder_is_asked() -> None:
    # The buyer IS the store's authority, so ATA(signer) and ATA(authority) collapse to
    # one address and the purchase would pay the buyer back. Observed live: /build
    # answered HTTP 200 to exactly this.
    builder, rpc = FakeBuilder(), FakeRpc()
    out = _prepare(builder, rpc, buyer=STORE_AUTHORITY)

    assert out["refused"] is True
    assert out["code"] == "plan-refused"
    assert "same-token-account" in out["reason"]
    assert "transaction" not in out
    assert builder.calls == [], "the plan reached the builder"
    assert rpc.calls == [], "the plan reached the network"


# --- 3. a receipt that did not pass ---------------------------------------------


def test_a_failed_receipt_returns_the_revert_class_and_no_transaction() -> None:
    rpc = FakeRpc(err={"InstructionError": [0, {"Custom": 6003}]})
    out = _prepare(FakeBuilder(), rpc)

    assert out["refused"] is True
    assert out["code"] == "receipt-failed"
    assert out["status"] == "fail"
    assert out["revert_class"]
    assert "transaction" not in out


# --- 4. the network is asserted, never inferred ---------------------------------


def test_a_missing_or_unknown_network_refuses_before_any_transport() -> None:
    # `unknown` is a legal answer and it refuses; a URL is not a network, because a fork
    # proxy answers at any hostname.
    for network in (_ABSENT, None, "unknown", "https://api.mainnet-beta.solana.com", 7):
        builder, rpc = FakeBuilder(), FakeRpc()
        overrides: dict[str, Any] = {} if network is _ABSENT else {"network": network}
        out = _prepare(builder, rpc, _drop_network=network is _ABSENT, **overrides)
        assert out["refused"] is True, network
        assert out["code"] == "network-not-asserted", network
        assert "transaction" not in out
        assert builder.calls == [] and rpc.calls == []


def test_an_unknown_store_refuses_rather_than_guessing_its_authority() -> None:
    builder, rpc = FakeBuilder(), FakeRpc()
    out = _prepare(builder, rpc, store="a-store-nobody-wired")
    assert out["refused"] is True
    assert out["code"] == "store-unknown"
    assert builder.calls == [] and rpc.calls == []


def test_a_buyer_that_is_not_a_pubkey_refuses() -> None:
    builder, rpc = FakeBuilder(), FakeRpc()
    out = _prepare(builder, rpc, buyer="not-a-pubkey")
    assert out["refused"] is True
    assert out["code"] == "argument-invalid"
    assert builder.calls == [] and rpc.calls == []


# --- 5. the boundary, asserted on the source itself -----------------------------


def _code_identifiers(path: Path) -> set[str]:
    """Every identifier the module's CODE uses. Docstrings and comments are ignored —
    they legitimately say "never signs"; only executable references count."""
    tree = ast.parse(path.read_text())
    identifiers: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Name):
            identifiers.add(node.id)
        elif isinstance(node, ast.Attribute):
            identifiers.add(node.attr)
        elif isinstance(node, ast.alias):
            identifiers.add(node.name.rsplit(".", 1)[-1])
            if node.asname:
                identifiers.add(node.asname)
    return identifiers


def test_no_signing_or_broadcast_identifier_exists_in_the_public_tool() -> None:
    root = Path(__file__).resolve().parent.parent
    sources = [
        root / "gecko" / "prepare_purchase.py",
        root / "gecko" / "providers" / "catalog_surface.py",
    ]
    forbidden = {
        "TransactionSigner",
        "SigningBackend",
        "Keypair",
        "sign_and_send",
        "sendTransaction",
        "send_transaction",
        "sign",
        "sign_transaction",
        "sign_message",
        "partial_sign",
        "new_signed",
        "secret_key",
        "from_seed",
        "broadcast",
    }
    for path in sources:
        leaked = forbidden & _code_identifiers(path)
        assert not leaked, f"{path.name} must not reference {sorted(leaked)} in code"


def test_the_tool_persists_nothing() -> None:
    root = Path(__file__).resolve().parent.parent / "gecko" / "prepare_purchase.py"
    used = _code_identifiers(root)
    assert not ({"open", "write_text", "write_bytes", "mkdir", "dump"} & used)


# --- the MCP surface actually serves it -----------------------------------------


def test_the_surface_dispatches_prepare_purchase() -> None:
    builder, rpc = FakeBuilder(), FakeRpc()
    surface = OrquestraCatalogSurface(
        purchase_build_call=builder, purchase_rpc_call=rpc
    )
    names = [tool["name"] for tool in surface.list_tools()]
    assert "prepare_purchase" in names

    tool = next(t for t in surface.list_tools() if t["name"] == "prepare_purchase")
    described = tool["description"].lower()
    for claim in ("unsigned", "you sign", "expires", "well-formed"):
        assert claim in described, claim
    assert tool["inputSchema"]["required"] == ["store", "product", "buyer", "network"]

    out = surface.call_tool(
        "prepare_purchase",
        {
            "store": "jonasbar",
            "product": "Water",
            "buyer": BUYER,
            "network": "mainnet",
            "rpc_url": RPC_URL,
        },
    )
    assert out["refused"] is False
    assert out["transaction"]["signed"] is False


# --- the affordance: what an agent does NEXT ----------------------------------
# The result already carried everything needed to PRODUCE a signature; it carried
# nothing an agent could act on. `who_signs` was prose. These pin the machine-readable
# next step and the submit target — the two fields that turn a check into a loop.


def test_the_result_says_what_to_do_next_in_a_shape_an_agent_can_act_on() -> None:
    out = _prepare()
    step = out["next_step"]

    # The order is the whole point: sign, verify, THEN submit.
    assert [s["step"] for s in step["do"]] == ["sign", "verify", "submit"]
    sign, verify, submit = step["do"]

    # SIGN carries the exact bytes to hand over — not a pointer, not a description.
    assert sign["transaction"] == out["transaction"]["unsigned_transaction"]
    assert sign["encoding"] == "base64"
    # VERIFY names our own keyless tool and the binding to check against.
    assert verify["tool"] == "verify_signed_transaction"
    assert verify["binding"] == out["binding"]
    # SUBMIT names the node these bytes can actually reach.
    assert submit["rpc_url"] == RPC_URL


def test_the_next_step_names_a_shape_rather_than_a_vendor() -> None:
    """Signer-agnostic on purpose. Three signers take the identical primitive (base64 in,
    signed base64 out), so naming one in the contract would make a fourth need a change
    from us. Known signers may be listed as EXAMPLES; none may be required."""
    step = _prepare()["next_step"]
    sign = step["do"][0]

    assert "tool" not in sign, "naming one signer's tool would be an integration"
    assert sign["signers_known_to_work"], "examples help; they must not be the contract"


def test_the_submit_target_is_the_node_that_was_actually_simulated_against() -> None:
    """The CALLER's node, echoed back — not the pinned public default.

    It matters most on a fork, where the RPC is somebody's own and appears nowhere else in
    the answer, so the one node that can accept the transaction would be missing from it.
    Asserted here on the supplied-URL case because the SSRF guard resolves DNS, and a
    made-up fork hostname is refused before any of this runs — correctly.
    """
    from gecko.prepare_purchase import DEFAULT_RPC_URLS

    out = _prepare()  # supplies RPC_URL explicitly

    assert out["submit"]["rpc_url"] == RPC_URL
    assert out["submit"]["rpc_url"] != DEFAULT_RPC_URLS["mainnet"], (
        "echoing the default instead of the caller's node would lose a fork's own RPC"
    )


def test_a_refusal_carries_no_next_step() -> None:
    """Nothing to sign, so nothing to do next. An affordance on a refusal is an
    invitation to act on bytes that do not exist."""
    out = _prepare(buyer=STORE_AUTHORITY)  # the self-paying refusal

    assert out["refused"] is True
    assert "next_step" not in out
    assert "submit" not in out
