"""Package it — export a provider-branded Agent Plugin from a comprehended surface.

The four-layer stack an agent ecosystem is converging on is **Find it** (agentic resource
discovery) → **Describe it** (an AI catalog) → **Package it** (agent plugins) → **Run it**
(MCP + agent skills), and adopting one never obligates anyone to the next. Gecko already
emitted Find it and Describe it (:mod:`gecko.agentnative`, :mod:`gecko.artifact`) and
serves Run it. **Package it was the empty layer**: everything we produced was ours to
host, and nothing was a thing a PROVIDER could drop into their own repository and publish
as theirs.

This builds that tree, and the design turns on one decision — the plugin carries the
**provider's** name, because they are the ones who publish it. That makes authorship the
sharp edge:

- The ``author`` is supplied by the caller or **absent**. It is never inferred from a
  display name or a domain. Putting words in a provider's mouth is the one failure this
  module must not have.
- The tree says, in the standard's own ``extensions`` slot, that Gecko generated it and
  from which surface. A reader who picks up a provider-branded plugin can find out where
  it came from without reading our source.

**Adopt, do not invent.** The manifest is Agent Plugins 1.0.0 against its published
schema; the host variants (``.claude-plugin/plugin.json``, ``gemini-extension.json``) are
the ones the standard's reference implementation ships; the card is A2A-shaped. The
``extensions`` slot is sanctioned for what the standard cannot express, so — unlike FDL
and A2A, where we had to argue for a field — nothing needs proposing upstream here.

**Control plane (invariant #1).** The tree carries the surface and its correctness
metadata. No response payloads, no balances, no user data, no secrets.

**Everything from a surface is untrusted.** Provider metadata is spec-derived, so every
emitted string goes through :func:`gecko.agentnative._safe` — the same anti-poisoning,
secret-redacting, markdown-neutralizing path every other emitted artifact uses. Sharing
that function is deliberate: a second copy of the rule is a second thing to drift.
"""

from __future__ import annotations

import json
import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any

from .agentnative import _safe

__all__ = [
    "PLUGIN_SCHEMA",
    "PluginExportError",
    "ProviderIdentity",
    "build_plugin",
    "write_plugin",
]

#: The published Agent Plugins schema. Pinned to a version, never to "latest": a tree we
#: hand a provider must keep meaning what it meant on the day we generated it.
PLUGIN_SCHEMA = "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json"

#: The plugin name becomes a directory under ``skills/`` and a key a host looks up, so it
#: is constrained to what is safe as both. Enforced rather than sanitized: silently
#: rewriting a name would produce a tree whose directory does not match its manifest.
_SAFE_NAME = re.compile(r"^[a-z0-9][a-z0-9._-]{0,62}$")

_DISCLOSURE = (
    "Generated by Gecko from this surface's own spec/IDL. It is not the provider's own "
    "word beyond what that surface states, and it carries no response payloads, balances, "
    "user data or secrets."
)

_NAME_CAP = 64
_DESC_CAP = 400


class PluginExportError(Exception):
    """A plugin tree could not be built."""


@dataclass(frozen=True)
class ProviderIdentity:
    """Who the plugin is for. Frozen: the field set IS what lands in the manifest.

    ``name`` is the machine identity (and a path segment); ``display_name`` is what a
    human reads. Neither is ever synthesized from the other, because a guess here is a
    guess about someone else's brand.
    """

    name: str
    display_name: str
    description: str
    homepage: str
    license: str = ""
    keywords: tuple[str, ...] = ()


def _manifest(
    provider: ProviderIdentity,
    *,
    version: str,
    author: str | None,
    generated_from: str | None,
) -> dict[str, Any]:
    manifest: dict[str, Any] = {
        "$schema": PLUGIN_SCHEMA,
        "name": provider.name,
        "version": version,
        "description": _safe(provider.description, _DESC_CAP),
    }
    # Absent, never guessed. See the module docstring: this is the one field where being
    # wrong misrepresents a third party rather than merely being unhelpful.
    if author:
        manifest["author"] = {"name": _safe(author, _NAME_CAP)}
    if provider.homepage:
        manifest["homepage"] = provider.homepage
    if provider.license:
        manifest["license"] = _safe(provider.license, _NAME_CAP)
    if provider.keywords:
        manifest["keywords"] = [_safe(k, _NAME_CAP) for k in provider.keywords]
    manifest["extensions"] = {
        "gecko": {
            "generated_by": "gecko",
            "generated_from": generated_from or provider.homepage or provider.name,
            "disclosure": _DISCLOSURE,
        }
    }
    return manifest


def _agent_card(
    provider: ProviderIdentity,
    *,
    version: str,
    mcp_url: str | None,
    skills: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    """An A2A-shaped card. Adopted, not invented — the field names are the spec's.

    ``capabilities`` is reported honestly: Gecko serves request/response over MCP and
    neither streams nor pushes, and a card that claimed otherwise would be a promise the
    surface cannot keep.
    """
    return {
        "name": _safe(provider.display_name, _NAME_CAP),
        "description": _safe(provider.description, _DESC_CAP),
        "url": mcp_url or provider.homepage,
        "version": version,
        "provider": {
            "organization": _safe(provider.display_name, _NAME_CAP),
            "url": provider.homepage,
        },
        "capabilities": {"streaming": False, "pushNotifications": False},
        "defaultInputModes": ["text"],
        "defaultOutputModes": ["text"],
        "skills": list(skills),
    }


def build_plugin(
    *,
    provider: ProviderIdentity,
    surface_files: Mapping[str, str],
    version: str = "0.1.0",
    author: str | None = None,
    mcp_url: str | None = None,
    generated_from: str | None = None,
    skills: Sequence[Mapping[str, Any]] = (),
) -> dict[str, str]:
    """Build the plugin tree as ``{relative path: content}``.

    Files-as-data rather than files-on-disk so the tree is fully testable without a
    filesystem, and so a caller can inspect or diff it before materializing it.

    ``surface_files`` is what :func:`gecko.agentnative.build_artifacts` returns (or the
    program-side equivalent). ``SKILL.md`` is re-homed under ``skills/<name>/`` where the
    standard expects it; everything else is carried at the root, where a discovery probe
    looks for it.
    """
    if not _SAFE_NAME.match(provider.name):
        raise ValueError(
            f"plugin name {provider.name!r} is not a safe directory name — "
            "lowercase letters, digits, dot, dash and underscore only"
        )

    files: dict[str, str] = {}
    for path, content in surface_files.items():
        if path.startswith("/") or ".." in path.split("/"):
            raise PluginExportError(f"surface file path escapes the tree: {path!r}")
        if path == "SKILL.md":
            files[f"skills/{provider.name}/SKILL.md"] = content
        else:
            files[path] = content

    manifest = _manifest(
        provider, version=version, author=author, generated_from=generated_from
    )
    files["plugin.json"] = json.dumps(manifest, indent=2) + "\n"

    # The host variants. Same identity, minus the fields those runtimes do not read — a
    # host that ignores a field is fine; a host that chokes on one is not.
    host = {k: v for k, v in manifest.items() if k not in ("$schema", "extensions")}
    files[".claude-plugin/plugin.json"] = json.dumps(host, indent=2) + "\n"
    files["gemini-extension.json"] = (
        json.dumps(
            {
                "name": manifest["name"],
                "version": manifest["version"],
                "description": manifest["description"],
            },
            indent=2,
        )
        + "\n"
    )

    files["agent-card.json"] = (
        json.dumps(
            _agent_card(provider, version=version, mcp_url=mcp_url, skills=skills),
            indent=2,
        )
        + "\n"
    )
    return files


def write_plugin(files: Mapping[str, str], out_dir: str) -> list[str]:
    """Materialize a built tree under ``out_dir``. Returns the paths written.

    Re-checks containment at write time. :func:`build_plugin` already refuses an unsafe
    name and an escaping surface path, but this function can be handed any mapping, and a
    path check that lives only at the far end of the pipeline is one refactor away from
    being skipped.
    """
    from pathlib import Path

    root = Path(out_dir).resolve()
    written: list[str] = []
    for relative, content in sorted(files.items()):
        target = (root / relative).resolve()
        if not target.is_relative_to(root):
            raise PluginExportError(f"path escapes the export root: {relative!r}")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(str(target.relative_to(root)))
    return written
