"""Lexical retrieval baseline over the frozen golden sets — the bar every semantic stage
must beat (plan §2). Thin transport: the metrics live in ``gecko.evaluate``.

Scores recall@k / MRR at depth >= 20 under each file's labeling session, BEFORE and AFTER
the 0/97 never-empty fix (both derived from one scored run — dropping fallback candidates
reproduces the pre-fix `score > 0` behaviour exactly). Writes a Markdown report to
``private/`` (gitignored — a benchmark log, not payload).

    uv run python scripts/golden_baseline.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from gecko.access import Session, public_session  # noqa: E402
from gecko.client import AgentApiClient  # noqa: E402
from gecko.evaluate import RECALL_KS, evaluate_golden, load_golden  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
GOLDEN = ROOT / "tests" / "fixtures" / "golden"
SCORE_DEPTH = max(RECALL_KS) + 10  # >= 20, uncensored above the deepest k

CASES = {
    "txodds": (
        ROOT / "tests" / "fixtures" / "txodds_docs.yaml",
        lambda: Session(jwt="recorded-mode", api_token="recorded-mode"),
        "18-op regression-guard proxy (real ~97-op TxODDS spec not committed)",
    ),
    "pegana": (
        ROOT / "tests" / "fixtures" / "pegana_openapi.json",
        public_session,
        "41-op spec, 26 usable under public read — least-bad committed full-size pool",
    ),
}


def _recall_line(block: dict) -> str:
    r = block["recall_at"]
    cells = " · ".join(f"@{k} {r[k]:.2f}" for k in RECALL_KS)
    return f"recall {cells} · MRR {block['mrr']:.3f}"


def _archetype_recall5(card: dict) -> dict[str, tuple[int, int]]:
    """(hits@5, n) per archetype over positive tasks, after-fix."""
    agg: dict[str, list[int]] = {}
    for r in card["per_task"]:
        if not r["expect_ops"]:
            continue
        hit5 = 1 if (r["rank"] is not None and r["rank"] <= 5) else 0
        h, n = agg.get(r["archetype"], [0, 0])
        agg[r["archetype"]] = [h + hit5, n + 1]
    return {k: (v[0], v[1]) for k, v in agg.items()}


def run() -> str:
    out: list[str] = [
        "# Lexical retrieval baseline — frozen golden sets",
        "",
        "Generated by `scripts/golden_baseline.py`. recall@k / MRR over positive tasks;",
        "out-of-scope tasks scored by the confidence-floor guard. `before_fix` = pre-0/97",
        "(`score > 0` drop → []); `after_fix` = never-empty fallback. Retrieval rank only —",
        "NOT first-call-correct.",
        "",
    ]
    for name, (spec, session_factory, pool_note) in CASES.items():
        client = AgentApiClient(str(spec), session=session_factory())
        tasks = load_golden(GOLDEN / f"{name}_tasks.jsonl")
        card = evaluate_golden(client, tasks, limit=SCORE_DEPTH)
        counts: dict[str, int] = {}
        for t in tasks:
            counts[t.archetype] = counts.get(t.archetype, 0) + 1
        out += [
            f"## {name}",
            f"- pool: {len(client.list_tools())} usable ops · {pool_note}",
            f"- tasks: {len(tasks)} ({card['n_positive']} positive, {card['n_oos']} out-of-scope) · "
            + ", ".join(f"{k}={v}" for k, v in sorted(counts.items())),
            f"- **before_fix**: {_recall_line(card['before_fix'])}",
            f"- **after_fix** : {_recall_line(card['after_fix'])}",
            "- out-of-scope pass-rate: "
            f"before {card['oos_pass_rate']['before_fix']:.2f} · "
            f"after {card['oos_pass_rate']['after_fix']:.2f}",
            "- recall@5 by archetype (after): "
            + ", ".join(
                f"{a} {h}/{n}" for a, (h, n) in sorted(_archetype_recall5(card).items())
            ),
            "",
            "| goal | archetype | rank(before→after) | via_fallback |",
            "|---|---|---|---|",
        ]
        for r in card["per_task"]:
            if not r["expect_ops"]:
                mark = "OOS-PASS" if r["hit"] else "OOS-FAIL(false-positive)"
                out.append(
                    f"| {r['goal']} | {r['archetype']} | {mark} "
                    f"(top1={r['top1']}, fallback={r['top1_is_fallback']}) | — |"
                )
            else:
                rb = r["rank_before_fix"]
                ra = r["rank"]
                out.append(
                    f"| {r['goal']} | {r['archetype']} | {rb}→{ra} | {r['via_fallback']} |"
                )
        out.append("")
    return "\n".join(out)


def main() -> None:
    report = run()
    dest = ROOT / "private" / "2026-07-01-lexical-baseline.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(report, encoding="utf-8")
    print(report)
    print(f"\nwrote {dest}")


if __name__ == "__main__":
    main()
