"""Lexical retrieval baseline over the frozen golden sets — the bar every semantic stage
must beat (plan §2). Thin transport: the metrics live in ``gecko.evaluate``.

Scores recall@k / MRR at depth >= 20 under each file's labeling session, under BOTH
readings of the same scored run: what the RANKER found (genuine hits) and what it looks
like when the 0/97 never-empty fallback's position is counted as a hit. The first is the
baseline; the second is here so the gap is visible. Writes a Markdown report to
``private/`` (gitignored — a benchmark log, not payload).

    uv run python scripts/golden_baseline.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from gecko.access import Session, public_session  # noqa: E402
from gecko.client import AgentApiClient  # noqa: E402
from gecko.evaluate import (  # noqa: E402
    RECALL_KS,
    evaluate_golden,
    load_golden,
    recall_summary,
)

ROOT = Path(__file__).resolve().parent.parent
GOLDEN = ROOT / "tests" / "fixtures" / "golden"
SCORE_DEPTH = max(RECALL_KS) + 10  # >= 20, uncensored above the deepest k

CASES = {
    "txodds": (
        ROOT / "tests" / "fixtures" / "txodds_docs.yaml",
        lambda: Session(jwt="recorded-mode", api_token="recorded-mode"),
        "18-op regression-guard proxy (real ~97-op TxODDS spec not committed)",
    ),
    "pegana": (
        ROOT / "tests" / "fixtures" / "pegana_openapi.json",
        public_session,
        "41-op spec, 26 usable under public read — least-bad committed full-size pool",
    ),
}


def _archetype_recall5(card: dict) -> dict[str, tuple[int, int]]:
    """(ranker hits@5, n) per archetype over positive tasks — genuine hits only.

    Under the fallback reading every paraphrase task scores a "hit" the moment nothing
    matched it, which is the opposite of what this table is for."""
    agg: dict[str, list[int]] = {}
    for r in card["per_task"]:
        if not r["expect_ops"]:
            continue
        rank = r["rank_ranker"]
        hit5 = 1 if (rank is not None and rank <= 5) else 0
        h, n = agg.get(r["archetype"], [0, 0])
        agg[r["archetype"]] = [h + hit5, n + 1]
    return {k: (v[0], v[1]) for k, v in agg.items()}


def run() -> str:
    out: list[str] = [
        "# Lexical retrieval baseline — frozen golden sets",
        "",
        "Generated by `scripts/golden_baseline.py`. recall@k / MRR over positive tasks;",
        "out-of-scope tasks scored by the confidence-floor guard. Retrieval rank only —",
        "NOT first-call-correct.",
        "",
        "**The baseline is the ranker's line — genuine hits only.** The with-fallback line",
        "counts the 0/97 never-empty candidate's position as a hit; it is printed for",
        "contrast and is not a retrieval number. Where the two differ, the difference is",
        "exactly the tasks marked `via_fallback` in the per-task table: nothing matched, so",
        "a query-independent candidate was appended. That reading is FLAT across k on these",
        "sets (the gold op is at rank 1 or it was manufactured) and it inverts real gains:",
        "an op that finally clears the intent gate stops the fallback firing and drops out.",
        "",
    ]
    for name, (spec, session_factory, pool_note) in CASES.items():
        client = AgentApiClient(str(spec), session=session_factory())
        tasks = load_golden(GOLDEN / f"{name}_tasks.jsonl")
        card = evaluate_golden(client, tasks, limit=SCORE_DEPTH)
        counts: dict[str, int] = {}
        for t in tasks:
            counts[t.archetype] = counts.get(t.archetype, 0) + 1
        out += [
            f"## {name}",
            f"- pool: {len(client.list_tools())} usable ops · {pool_note}",
            f"- tasks: {len(tasks)} ({card['n_positive']} positive, {card['n_oos']} out-of-scope) · "
            + ", ".join(f"{k}={v}" for k, v in sorted(counts.items())),
            recall_summary(card),
            "- out-of-scope pass-rate: "
            f"ranker {card['oos_pass_rate']['ranker']:.2f} · "
            f"with-fallback {card['oos_pass_rate']['with_fallback']:.2f}",
            "- ranker recall@5 by archetype: "
            + ", ".join(
                f"{a} {h}/{n}" for a, (h, n) in sorted(_archetype_recall5(card).items())
            ),
            "",
            "| goal | archetype | rank(ranker→with fallback) | via_fallback |",
            "|---|---|---|---|",
        ]
        for r in card["per_task"]:
            if not r["expect_ops"]:
                mark = "OOS-PASS" if r["hit_ranker"] else "OOS-FAIL(false-positive)"
                out.append(
                    f"| {r['goal']} | {r['archetype']} | {mark} "
                    f"(top1={r['top1']}, fallback={r['top1_is_fallback']}) | — |"
                )
            else:
                out.append(
                    f"| {r['goal']} | {r['archetype']} | "
                    f"{r['rank_ranker']}→{r['rank_with_fallback']} | {r['via_fallback']} |"
                )
        out.append("")
    return "\n".join(out)


def main() -> None:
    report = run()
    dest = ROOT / "private" / "2026-07-01-lexical-baseline.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(report, encoding="utf-8")
    print(report)
    print(f"\nwrote {dest}")


if __name__ == "__main__":
    main()
