"""Generate the module index — the thing this repo sells, pointed at itself.

`gecko/` holds 165 modules and CLAUDE.md names 24 of them. The cost is not
comprehension: the docstrings here are unusually good. The cost is DISCOVERY —
three to five greps before every task, just to learn whether a thing already
exists. That is the same failure we charge providers to fix on their surface.

Emits `docs/module-index.md`: one row per module, its first docstring line, and
who imports it. Everything is read from the source, so it cannot drift into a
lie the way a hand-maintained table does; CI regenerates and diffs it.

    uv run python scripts/module_index.py            # write the file
    uv run python scripts/module_index.py --check    # CI: fail if stale
"""

from __future__ import annotations

import argparse
import ast
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = ROOT / "gecko"
OUT = ROOT / "docs" / "module-index.md"
HEADER = "<!-- generated by scripts/module_index.py — do not edit by hand -->"


def _summary(path: Path) -> str:
    """The module's first docstring line, or '' when it has none."""
    try:
        doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8")))
    except (SyntaxError, OSError):
        return ""
    if not doc:
        return ""
    first = doc.strip().splitlines()[0].strip()
    # A summary wider than the column is worse than a truncated one: the table
    # stops being scannable, which is the only reason this file exists.
    return first if len(first) <= 96 else first[:93].rstrip() + "…"


def _local_imports(path: Path, names: set[str]) -> set[str]:
    """Sibling modules this file imports — the edge that answers 'who uses this?'."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, OSError):
        return set()
    found: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            head = node.module.split(".")[0] if node.level else node.module
            tail = node.module.split(".")[-1]
            for cand in (head, tail):
                if cand in names:
                    found.add(cand)
        elif isinstance(node, ast.Import):
            for alias in node.names:
                tail = alias.name.split(".")[-1]
                if tail in names:
                    found.add(tail)
    return found - {path.stem}


def build() -> str:
    modules = sorted(p for p in PKG.glob("*.py") if p.stem != "__init__")
    names = {p.stem for p in modules}
    importers: dict[str, set[str]] = defaultdict(set)
    for path in modules:
        for dep in _local_imports(path, names):
            importers[dep].add(path.stem)

    lines = [
        HEADER,
        "",
        "# Module index",
        "",
        f"{len(modules)} modules in `gecko/`, generated from their own docstrings.",
        "`used by` counts sibling modules that import it — a 0 means nothing in the",
        "package depends on it, which is worth a look before you add a caller.",
        "",
        "| module | what it is | used by |",
        "| --- | --- | --- |",
    ]
    for path in modules:
        who = sorted(importers.get(path.stem, ()))
        shown = ", ".join(f"`{w}`" for w in who[:3])
        if len(who) > 3:
            shown += f" +{len(who) - 3}"
        summary = _summary(path).replace("|", "\\|") or "_(no docstring)_"
        lines.append(
            f"| `{path.stem}` | {summary} | {len(who)}{' · ' + shown if who else ''} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = ap.parse_args(argv)
    fresh = build()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != fresh:
            print(
                f"{OUT.relative_to(ROOT)} is stale — run: uv run python scripts/module_index.py"
            )
            return 1
        print(f"{OUT.relative_to(ROOT)} is current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(fresh, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} — {fresh.count(chr(10) + '| `')} modules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
