"""Generate the module index — the thing this repo sells, pointed at itself.

`gecko/` holds 233 modules and CLAUDE.md names 24 of them. The cost is not
comprehension: the docstrings here are unusually good. The cost is DISCOVERY —
three to five greps before every task, just to learn whether a thing already
exists. That is the same failure we charge providers to fix on their surface.

Emits `docs/module-index.md`: one row per module, its first docstring line, and
who imports it. Everything is read from the source, so it cannot drift into a
lie the way a hand-maintained table does; CI regenerates and diffs it.

WHY `rglob` AND NOT `glob`, because the first version got this wrong. Scanning
only `gecko/*.py` left 67 files under `gecko/**/` out of the IMPORTER population,
so a module used only from `providers/` or `sandbox/` printed `0 importers` and
read as dead. The arithmetic was right and the population was wrong — the same
failure the module index exists to make visible, committed by the index itself.
A "0" here is a claim about every file in the package or it is noise.

    uv run python scripts/module_index.py            # write the file
    uv run python scripts/module_index.py --check    # CI: fail if stale
"""

from __future__ import annotations

import argparse
import ast
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = ROOT / "gecko"
OUT = ROOT / "docs" / "module-index.md"
HEADER = "<!-- generated by scripts/module_index.py — do not edit by hand -->"


def _summary(path: Path) -> str:
    """The module's first docstring line, or '' when it has none."""
    try:
        doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8")))
    except (SyntaxError, OSError):
        return ""
    if not doc:
        return ""
    first = doc.strip().splitlines()[0].strip()
    # A summary wider than the column is worse than a truncated one: the table
    # stops being scannable, which is the only reason this file exists.
    return first if len(first) <= 96 else first[:93].rstrip() + "…"


def _module_name(path: Path) -> str:
    """`gecko/providers/cli.py` -> `providers.cli`. The dotted name a reader greps for."""
    return ".".join(path.relative_to(PKG).with_suffix("").parts)


def _resolve(module: str | None, level: int, importer: str) -> str:
    """The absolute in-package name a single import refers to.

    `level` is the leading-dot count, so a relative import has to be resolved against
    the importing module's own package or it silently lands on the wrong row: inside
    `providers/cli.py`, `from .let_me_buy import X` is `providers.let_me_buy`, while
    `from ..graph import Y` is `graph`.
    """
    if not level:
        base = (module or "").removeprefix("gecko.")
        return base if base != "gecko" else ""
    parts = importer.split(".")[:-1]  # the importing module's package
    up = parts[: len(parts) - (level - 1)] if level > 1 else parts
    return ".".join([*up, *(module.split(".") if module else [])])


def _local_imports(path: Path, names: set[str]) -> set[str]:
    """In-package modules this file imports — the edge that answers 'who uses this?'.

    Resolves to the LONGEST known prefix, so `from .configs.orquestra import x` credits
    `providers.configs` when that is the module that exists.
    """
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, OSError):
        return set()
    me = _module_name(path)
    found: set[str] = set()

    def _credit(dotted: str) -> None:
        parts = dotted.split(".")
        for cut in range(len(parts), 0, -1):
            candidate = ".".join(parts[:cut])
            if candidate in names:
                found.add(candidate)
                return

    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom):
            _credit(_resolve(node.module, node.level, me))
        elif isinstance(node, ast.Import):
            for alias in node.names:
                _credit(alias.name.removeprefix("gecko."))
    return found - {me}


def build() -> str:
    modules = sorted(
        p
        for p in PKG.rglob("*.py")
        if p.stem != "__init__" and "__pycache__" not in p.parts
    )
    names = {_module_name(p) for p in modules}
    importers: dict[str, set[str]] = defaultdict(set)
    for path in modules:
        for dep in _local_imports(path, names):
            importers[dep].add(_module_name(path))

    lines = [
        HEADER,
        "",
        "# Module index",
        "",
        f"{len(modules)} modules in `gecko/` (subpackages included), from their own docstrings.",
        "`used by` counts sibling modules that import it — a 0 means nothing in the",
        "package depends on it, which is worth a look before you add a caller.",
        "",
        "| module | what it is | used by |",
        "| --- | --- | --- |",
    ]
    for path in modules:
        who = sorted(importers.get(_module_name(path), ()))
        shown = ", ".join(f"`{w}`" for w in who[:3])
        if len(who) > 3:
            shown += f" +{len(who) - 3}"
        summary = _summary(path).replace("|", "\\|") or "_(no docstring)_"
        lines.append(
            f"| `{_module_name(path)}` | {summary} | "
            f"{len(who)}{' · ' + shown if who else ''} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = ap.parse_args(argv)
    fresh = build()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != fresh:
            print(
                f"{OUT.relative_to(ROOT)} is stale — run: uv run python scripts/module_index.py"
            )
            return 1
        print(f"{OUT.relative_to(ROOT)} is current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(fresh, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} — {fresh.count(chr(10) + '| `')} modules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
